# ML Zoomcamp Homework 01

Questions: [link](https://github.com/alexeygrigorev/mlbookcamp-code/blob/master/course-zoomcamp/cohorts/2022/01-intro/homework.md)

## Import python modules

In [ ]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns

## Q1. What's the version of NumPy that you installed?

Answer: `1.21.6`

In [ ]:
np.__version__

'1.21.6'

### Read csv into dataframe

Data Source [link](https://raw.githubusercontent.com/alexeygrigorev/mlbookcamp-code/master/chapter-02-car-price/data.csv)

In [ ]:
df = pd.read_csv(r"https://raw.githubusercontent.com/alexeygrigorev/mlbookcamp-code/master/chapter-02-car-price/data.csv")

In [ ]:
df.head()

Make       Model  Year             Engine Fuel Type  Engine HP  \
0  BMW  1 Series M  2011  premium unleaded (required)      335.0   
1  BMW    1 Series  2011  premium unleaded (required)      300.0   
2  BMW    1 Series  2011  premium unleaded (required)      300.0   
3  BMW    1 Series  2011  premium unleaded (required)      230.0   
4  BMW    1 Series  2011  premium unleaded (required)      230.0   

   Engine Cylinders Transmission Type     Driven_Wheels  Number of Doors  \
0               6.0            MANUAL  rear wheel drive              2.0   
1               6.0            MANUAL  rear wheel drive              2.0   
2               6.0            MANUAL  rear wheel drive              2.0   
3               6.0            MANUAL  rear wheel drive              2.0   
4               6.0            MANUAL  rear wheel drive              2.0   

                         Market Category Vehicle Size Vehicle Style  \
0  Factory Tuner,Luxury,High-Performance      Compact         Coupe   
1                     Luxury,Performance      Compact   Convertible   
2                Luxury,High-Performance      Compact         Coupe   
3                     Luxury,Performance      Compact         Coupe   
4                                 Luxury      Compact   Convertible   

   highway MPG  city mpg  Popularity   MSRP  
0           26        19        3916  46135  
1           28        19        3916  40650  
2           28        20        3916  36350  
3           28        18        3916  29450  
4           28        18        3916  34500

## Q2. How many records are in the dataset?

Answer: `11914`

In [ ]:
df.shape[0]

11914

## Q3. Who are the most popular car manufacturers (top-3) according to the dataset?

Answer: `Chevrolet, Ford, Volkswagen`

In [ ]:
df.groupby('Make').size().reset_index(name='counts').sort_values(['counts'], ascending=False).head(3)

Make  counts
9    Chevrolet    1123
14        Ford     881
46  Volkswagen     809

## Q4. What's the number of unique Audi car models in the dataset?

Answer: `34` (Closest)

In [ ]:
df.loc[df['Make'] == 'BMW'].Model.unique()

array(['1 Series M', '1 Series', '2 Series', '3 Series Gran Turismo',
       '3 Series', '4 Series Gran Coupe', '4 Series',
       '5 Series Gran Turismo', '5 Series', '6 Series Gran Coupe',
       '6 Series', '7 Series', '8 Series', 'ActiveHybrid 5',
       'ActiveHybrid 7', 'ActiveHybrid X6', 'ALPINA B6 Gran Coupe',
       'ALPINA B7', 'Alpina', 'i3', 'M2', 'M3', 'M4 GTS', 'M4', 'M5',
       'M6 Gran Coupe', 'M6', 'M', 'X1', 'X3', 'X4', 'X5 M', 'X5', 'X6 M',
       'X6', 'Z3', 'Z4 M', 'Z4', 'Z8'], dtype=object)

In [ ]:
len(df.loc[df['Make'] == 'BMW'].Model.unique())

39

## Q5. How many columns in the dataset have missing values?

Answer: `5`

In [ ]:
df.isna().sum()[df.isna().sum() > 0]

Engine Fuel Type       3
Engine HP             69
Engine Cylinders      30
Number of Doors        6
Market Category     3742
dtype: int64

In [ ]:
len(df.isna().sum()[df.isna().sum() > 0])

5

## Q6. Calculate
* Find the median value of "Engine Cylinders" column in the dataset.
* Next, calculate the most frequent value of the same "Engine Cylinders".
* Use the fillna method to fill the missing values in "Engine Cylinders" with the most frequent value from the previous step.
* Now, calculate the median value of "Engine Cylinders" once again.

Answer: `No`

In [ ]:
df['Engine Cylinders'].median()

6.0

In [ ]:
df['Engine Cylinders'].mode()[0]

4.0

In [ ]:
df['Engine Cylinders'].fillna(df['Engine Cylinders'].mode()[0], inplace=True)

In [ ]:
df['Engine Cylinders'].median()

6.0

## Q7. Calculate
* Select all the "Lotus" cars from the dataset.
* Select only columns "Engine HP", "Engine Cylinders".
* Now drop all duplicated rows using drop_duplicates method (you should get a dataframe with 9 rows).
* Get the underlying NumPy array. Let's call it X.
* Compute matrix-matrix multiplication between the transpose of X and X. To get the transpose, use X.T. Let's call the result XTX.
* Invert XTX.
* Create an array y with values [1100, 800, 750, 850, 1300, 1000, 1000, 1300, 800].
* Multiply the inverse of XTX with the transpose of X, and then multiply the result by y. Call the result w.
* What's the value of the first element of w?

Answer: `4.5949`

In [ ]:
df2 = df.loc[df['Make'] == 'Lotus']

In [ ]:
df2 = df2[["Engine HP", "Engine Cylinders"]]

In [ ]:
df2.drop_duplicates(inplace=True, ignore_index=True)
df2

Engine HP  Engine Cylinders
0      189.0               4.0
1      218.0               4.0
2      217.0               4.0
3      350.0               8.0
4      400.0               6.0
5      276.0               6.0
6      345.0               6.0
7      257.0               4.0
8      240.0               4.0

In [ ]:
X = df2.values
X

array([[189.,   4.],
       [218.,   4.],
       [217.,   4.],
       [350.,   8.],
       [400.,   6.],
       [276.,   6.],
       [345.,   6.],
       [257.,   4.],
       [240.,   4.]])

In [ ]:
XTX = X.T.dot(X)
XTX

array([[7.31684e+05, 1.34100e+04],
       [1.34100e+04, 2.52000e+02]])

In [ ]:
XTX_inv = np.linalg.inv(XTX)
XTX_inv

array([[ 5.53084235e-05, -2.94319825e-03],
       [-2.94319825e-03,  1.60588447e-01]])

In [ ]:
y = [1100, 800, 750, 850, 1300, 1000, 1000, 1300, 800]

In [ ]:
w = XTX_inv.dot(X.T).dot(y)
w

array([  4.59494481, -63.56432501])

In [ ]:
w[0]

4.594944810094551

## Ends